apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: react-app-clusterrole
  namespace: kube-system  # Optional: specify if needed
rules:
  - apiGroups: [""]  # "" indicates the core API group
    resources: ["pods", "services", "replicationcontrollers"]
    verbs: ["get", "list", "watch", "create", "update", "delete"]
  
  - apiGroups: ["apps"]
    resources: ["deployments", "statefulsets"]
    verbs: ["get", "list", "watch", "create", "update", "delete"]
  
  - apiGroups: ["extensions"]
    resources: ["ingresses"]
    verbs: ["get", "list", "watch", "create", "update", "delete"]
  
  - apiGroups: ["batch"]
    resources: ["jobs", "cronjobs"]
    verbs: ["get", "list", "watch", "create", "update", "delete"]
  
  - apiGroups: ["networking.k8s.io"]
    resources: ["networkpolicies"]
    verbs: ["get", "list", "watch", "create", "update", "delete"]
