apiVersion: v1
kind: Service
metadata:
  labels:
    app: react-app
  name: react-app-service
spec:
  ports:
  - port: 3000
    protocol: TCP
    targetPort: 3000
  selector:
    app: react-app
  type: LoadBalancer
